# Generated by Django 3.1.3 on 2023-02-24 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motocicleta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('marca', models.TextField(default='')),
                ('modelo', models.TextField(default='')),
                ('motor', models.TextField(default='')),
                ('consumo_g', models.PositiveSmallIntegerField(default='0')),
                ('capacidad_g', models.FloatField(default='')),
                ('cilindraje', models.IntegerField(default='')),
                ('version', models.TextField(default='')),
                ('color', models.TextField(default='')),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
    ]
