# Generated by Django 3.1.3 on 2023-03-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorcycles', '0002_auto_20230224_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motocicleta',
            name='capacidad_g',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='motocicleta',
            name='cilindraje',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='motocicleta',
            name='consumo_g',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
