# Generated by Django 3.1.3 on 2023-03-24 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motorcycles', '0003_auto_20230324_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motocicleta',
            old_name='capacidad_g',
            new_name='capacidadg',
        ),
        migrations.RenameField(
            model_name='motocicleta',
            old_name='consumo_g',
            new_name='consumog',
        ),
    ]
