apiVersion: apps/v1
kind: Deployment
metadata:
  name: i2k3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: i2k3
  template:
    metadata:
      labels:
        app: i2k3
    spec:
      containers:
      - image: okteto.dev/i2k3:latest
        name: i2k3
        envFrom:
        - configMapRef:
            name: i2k3-config
        livenessProbe:
          httpGet:
            path: /ht/
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---

apiVersion: v1
kind: Service
metadata:
  name: i2k3
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "i2k3"
    port: 8080
  selector:
    app: i2k3